#!/usr/bin/python
import sys          as _sys
import time         as _time
import PIL.Image    as _image

# must match panel configuration in source
_COLS = 12
_ROWS = 11

def main() :
    print '/* Generated by Image2RGBArray on %s */' % _time.asctime()
    print
    print 'static const RGB kImages[][kMatrixPixels] = {'
    names = _sys.argv[1:]
    names.sort()
    tile_count = 0
    for name in _sys.argv[1:] :
        print >> _sys.stderr, 'Loading: %s' % name
        im = _image.open(name, 'r')
        pix = im.load()
        cols, rows = im.size
        print >> _sys.stderr, 'Image Size: %dx%d' % (cols, rows) 
        x = 0
        while  x < cols :
          tile_count += 1
          print '  {'
          for col in xrange(_COLS) :
              for y in xrange(rows) :
                  r, g, b = pix[x, y]
                  print '    {%d, %d, %d},' % (r, g, b)
              x += 1
          print '  },'

    print '};'
    print
    print 'static const size_t kImageCount = %d;' % tile_count


if __name__ == '__main__' :
    main()
